interface_name: [lo]
n3_address: 127.0.0.1
xdp_attach_mode: generic
api_address: :8080
pfcp_address: 127.0.0.1:8805
pfcp_node_id: 127.0.0.1
metrics_address: :9090
qer_map_size: 1024
far_map_size: 1024
pdr_map_size: 1024
feature_ueip: false
feature_ftup: false
gtp_peer: []
echo_interval: 10
heartbeat_interval: 5
heartbeat_retries: 3
heartbeat_timeout: 5
logging_level: info
ueip_pool: 10.60.0.0/24
teid_pool: 65535
resize_ebpf_maps: false
